import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {type: 'doc', id: 'getting-started/overview'},
      items: [
        'getting-started/create-account',
        'getting-started/choose-plan',
        'getting-started/download-desktop-app',
        'getting-started/pair-your-first-booth',
        'getting-started/access-dashboard',
        'getting-started/your-first-session',
        'getting-started/video-walkthrough',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      link: {type: 'doc', id: 'use-cases/overview'},
      items: [
        'use-cases/self-service-photobooth',
        'use-cases/event-rental',
        'use-cases/multi-booth-studio',
        'use-cases/pop-up-booth',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/overview'},
      items: [
        'tutorials/set-up-a-booth',
        'tutorials/design-a-print-template',
        'tutorials/customise-kiosk-screens',
        'tutorials/create-a-payment-gateway',
        'tutorials/accept-payments',
        'tutorials/payment-setups-by-use-case',
        'tutorials/run-an-event',
        'tutorials/sell-sessions-online',
        'tutorials/studio-mode',
        'tutorials/sell-ai-portraits',
        'tutorials/frame-lab',
        'tutorials/add-or-move-a-computer',
        'tutorials/connect-a-coin-or-card-reader',
      ],
    },
    {
      type: 'category',
      label: 'Dashboard',
      link: {type: 'doc', id: 'dashboard/overview'},
      items: [
        'dashboard/dashboard-home',
        'dashboard/events',
        'dashboard/booth-management',
        'dashboard/booth-pricing',
        'dashboard/device-management',
        'dashboard/transactions',
        'dashboard/vouchers',
        'dashboard/marketing-studio',
        'dashboard/gallery',
        'dashboard/health',
        'dashboard/billing',
        {
          type: 'category',
          label: 'Pix Design',
          link: {type: 'doc', id: 'dashboard/pix-design/overview'},
          items: [
            'dashboard/pix-design/creating-templates',
            'dashboard/pix-design/folders-and-collections',
            'dashboard/pix-design/assigning-templates',
            'dashboard/pix-design/ui-editor',
            'dashboard/pix-design/filters-and-overlays',
            'dashboard/pix-design/microsite',
            'dashboard/pix-design/pix-ai',
          ],
        },
        'dashboard/settings',
      ],
    },
    {
      type: 'category',
      label: 'Desktop App',
      link: {type: 'doc', id: 'desktop-app/overview'},
      items: [
        'desktop-app/installation',
        {
          type: 'category',
          label: 'Camera Setup',
          items: [
            'desktop-app/camera-setup/canon-eos',
            'desktop-app/camera-setup/webcam-fallback',
            'desktop-app/camera-setup/camera-settings',
          ],
        },
        'desktop-app/printer-setup',
        {
          type: 'category',
          label: 'Session Flow',
          link: {type: 'doc', id: 'desktop-app/session-flow/overview'},
          items: [
            'desktop-app/session-flow/home-screen',
            'desktop-app/session-flow/payment',
            'desktop-app/session-flow/template-selection',
            'desktop-app/session-flow/capture-modes',
            'desktop-app/session-flow/review-and-adjust',
            'desktop-app/session-flow/filters',
            'desktop-app/session-flow/sharing',
          ],
        },
        'desktop-app/studio-sessions',
        'desktop-app/event-video-modes',
        'desktop-app/licence-on-the-booth',
        'desktop-app/offline-mode',
        'desktop-app/hardware-payments',
        'desktop-app/admin-panel',
        'desktop-app/software-updates',
        'desktop-app/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Plans & Billing',
      items: [
        'pricing/plans',
        'pricing/feature-comparison',
        'pricing/billing-faq',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/booth-operations-checklist',
        'guides/multi-booth-setup',
        'guides/payment-gateway-setup',
        'guides/branding-your-booth',
        'guides/shared-printer',
        'guides/connect-an-ai-assistant',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/system-requirements',
        'reference/supported-cameras',
        'reference/supported-printers',
        'reference/public-links',
        'reference/glossary',
      ],
    },
  ],
};

export default sidebars;
